### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by Xin94babala** [baldassarreFe/python-pankakes#1]
Hello, I have not found which paper your code originated from.  Can you post the article link? Thank you very much!

**Comment by baldassarreFe** [comment]
Hi, this is just a personal repo with no paper or article attached. For some algorithms, you'll find a bit of explanation in the respective folders, e.g. [here](https://github.com/baldassarreFe/python-pancakes/tree/master/Hungarian%20Alorithm%20for%20Task%20Assignment)
